language: go

sudo: false

go:
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - cd $GOPATH/src/github.com/mattn/goveralls 
  - git checkout multiple-packages
  - cd $GOPATH/src/github.com/redtankd/go-test

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci