language: go

sudo: false

go:
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  # goveralls don't support multiple package repository.
  # - $HOME/gopath/bin/goveralls -service=travis-ci
  - ./test-cover.sh